### ISSUE TITLE
Bowl of Promises tiers not crafting correctly on servers

### ISSUE THREAD

**Issue by XeramHosting** [rubensworks/EvilCraft#1039]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When trying to craft different tiers of Bowl of Promises using the correct tiers of promises the craft doesn't go through as expected and instead crafts Tier 1 every time.

#### Steps to reproduce the problem:

1. Make a bowl of dusted promises
2. Make a Promise of Tenacity 2 or higher
3. Throw both into a blood infuser with the right amount of blood
4. Get a Tier 1 bowl

#### Expected behaviour:

The result of the afforementioned craft should be a tier 2 bowl but it consistently produces a tier 1 bowl until the server is restarted. This does not seem to happen on a SP world as far as I could tell, and does happen with just EvilCraft and it's dependencies installed.
____

#### Versions:

- This mod: 47.3.5
- Minecraft: 1.20.1
- Forge: 1.2.43

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This should not be possible due to this piece of code: https://github.com/CyclopsMC/EvilCraft/blob/master-1.20-lts/src/main/java/org/cyclops/evilcraft/blockentity/BlockEntityBloodInfuser.java#L154-L155

Do you by any chance have some mod in your pack that interacts with or modifies how minecraft handles recipes, such as a caching mechanism? Because this could break things if that mod does not correctly check the inventory.

In any case, can you try reproducing the problem without any other mods installed? (I could not on my end)
If it can't be reproduced, I recommend looking for the mod that breaks things, and report it to their issue tracker.

<blockquote><img src="https://opengraph.githubassets.com/b68467945a1b3af38648f30e9ed10e75ca01c91e3600f9c53628c51331c3c7e2/CyclopsMC/EvilCraft" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EvilCraft/blob/master-1.20-lts/src/main/java/org/cyclops/evilcraft/blockentity/BlockEntityBloodInfuser.java">EvilCraft/src/main/java/org/cyclops/evilcraft/blockentity/BlockEntityBloodInfuser.java at master-1.20-lts · CyclopsMC/EvilCraft</a></strong></div><div>An evil mod for Minecraft. Contribute to CyclopsMC/EvilCraft development by creating an account on GitHub.</div></blockquote>

**Comment by KakashoLin** [comment]
If you are also using https://www.curseforge.com/minecraft/mc-mods/recipe-essentials-forge-fabric, it might not be compatible. 

<blockquote><img src="https://media.forgecdn.net/avatars/thumbnails/871/402/256/256/638289037640254884.png" width="48" align="right"><div>CurseForge</div><div><strong><a href="/minecraft/mc-mods/recipe-essentials-forge-fabric">Recipe Essentials[Forge/Fabric]</a></strong></div><div>Essential fixes and improvements around recipes and crafting
20.0M Downloads | Mods</div></blockquote>
