### ISSUE TITLE
Option to turn off or tune down the annoying netherfish spawn

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [rubensworks/EvilCraft#1059]
When you have 3x3 or 5x5 mining tools with efficiency 5+ and you almost instant mine the blocks in Nether, the netherfish spawn en masse.

THey are absolutely annoying to deal with to the point where turning off the mod is the better option.

Please add an option to tune down the spawn of Netherfish or turn them completely off.

**Comment by rubensworks** [comment]
All worldgen can be fully configured using datapacks since recent MC versions.
The relevant file you need is here: https://github.com/CyclopsMC/EvilCraft/blob/master-1.21/src/main/resources/data/evilcraft/worldgen/placed_feature/ore_infested_nether.json
Does this solve your problem?

<blockquote><img src="https://opengraph.githubassets.com/0d810bdb4bb44c81b5e105178b43e8fe685f791e1a6e58033e8b02d03f810aaa/CyclopsMC/EvilCraft" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EvilCraft/blob/master-1.21/src/main/resources/data/evilcraft/worldgen/placed_feature/ore_infested_nether.json">EvilCraft/src/main/resources/data/evilcraft/worldgen/placed_feature/ore_infested_nether.json at master-1.21 · CyclopsMC/EvilCraft</a></strong></div><div>An evil mod for Minecraft. Contribute to CyclopsMC/EvilCraft development by creating an account on GitHub.</div></blockquote>

**Comment by Unrepentant-Atheist** [comment]
Well, maybe, if I knew how do do a datapack..., sure. Why not provide one on github, with default values, so folks can tune them to their liking?+

**Comment by rubensworks** [comment]
There are many guides for datapacks out there.
Here's a good one: https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack

Note to self: check if default spawn rates of infested nether blocks need to be lowered.

**Comment by rubensworks** [comment]
Done in 7d52b13f46f94643e6d98badf2bcf30b5933ff47

**Comment by Unrepentant-Atheist** [comment]
That's for 1.21, I play on 1.20.1 =( and am too stupid to get a datapack working.

**Comment by rubensworks** [comment]
Sure, I can backport it.
