### ISSUE TITLE
Dark Book:  Extractor should be discussed earlier, spirits later.

### ISSUE THREAD

**Issue by MentalMouse** [rubensworks/EvilCraft#373]
In the Dark Book, the Blood Extractor is described very late.  Given how fundamental it is, it (also the claws needed for it, and even the Vein Sword) should be described with the earliest discussion of blood.

Similarly, spirits really shouldn't be First Age stuff at all (that should be blood), but much later -- there's nothing you can actually do with them until you create at least a Reincarnator if not a Soul Furnace, both of which require extensive blood work.  Not to mention finding or making a Box of Eternal Closure!

**Comment by rubensworks** [comment]
You're right, I noticed a lot of people not finding information on how to obtain Blood right away.

But for the spirits, they _are_ first age, because lore-wise they exist long before the author of the book and his blood-adventures. The author of the book just discovers some way to (ab)use them with blood (reanimator, spirit furnace).

**Comment by MentalMouse** [comment]
Thematically, it makes just as much sense for the Dark One to start off collecting and extracting blood, then progress to manipulating spirits.  Perhaps it was their experience of the VP's vengance spirits that turned their interest to the immaterial, eventually leading to the development of the BoEC, and the discovery of more manipulable creature spirits.
