### ISSUE TITLE
Crash upon placing Sanguinary Environmental Accumulator

### ISSUE THREAD

**Issue by squirrelkiller** [rubensworks/EvilCraft#404]
Forge log link: http://pastebin.com/FzSz0345

Crash log: http://pastebin.com/hH5WHU7M

Problem: Crash upon Sanguinary Environmental Accumulator (that's the name right? It is the Blood Version of the thing found in Dark Temples).

Expected behaviour: The game does not crash

Steps to reproduce the problem:
- Cheat in offending block
- Place it
- Glare at screen upon crash
- Be angry at mod for breaking

Notes: I feel like 1.9.4 Evilcraft does not want me to make videos. Just saying. Like if you don't want me to you can ask me not to it is totally cool.

**Comment by rubensworks** [comment]
This is probably caused by a Vanilla/Forge bug, but I added an extra check to make sure that it doesn't happen anymore.
(I know, there have been quite a lot of bugs lately, I guess that's normal when the mod just survived two major Minecraft updates ;-) )

You can find the latest dev build here: https://dl.bintray.com/cyclopsmc/dev/org/cyclops/evilcraft/EvilCraft/1.9.4-0.10.2-403/
I won't publish a new public patch release just yet.
