### ISSUE TITLE
[1.9.4] Crash with boundBloodDrop - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by JCMais** [rubensworks/EvilCraft#418]
Forge log link: https://gist.github.com/JCMais/cb0ee1afd9eec2574246b2e9495579c1

Problem: After binding the boundBloodDrop item to my blood magic soul network the server crashes.

Expected behaviour: It should not crash.

Steps to reproduce the problem:
1. Craft/cheat a boundBloodDrop
2. Bind it to your soul network (sneak+right click)
3. Wait
4. Crash
~~5. Annoy your friends crashing the server while they are trying to play~~

**Comment by rubensworks** [comment]
That's strange, just looked at the BM source code, and it is crashing on a method that doesn't exist, while the method actually does exist.
Is the rest of BM working normally? It is possible that they broke something on their end.

**Comment by Zaweri** [comment]
The rest of Blood Magic works on this pack (I am on the same server as him and he kept crashing the server when he had it in his inventory and he joined the server).

**Comment by digitalseraphim** [comment]
It's a version issue. The code has been fixed to work with the latest version of Blood Magic, but these fixed haven't made it into an available build yet. The method in question used to take a string, but now it takes an "IID" (or something like that). 2 options I know of: build it yourself from latest source (I have not tried this and the code may not be stable, so try at your own risk and make backups of your world if you care) , or revert Blood Magic to build 44

**Comment by rubensworks** [comment]
Tested this with the latest BM version (BloodMagic-1.9.4-2.0.2-48) in SMP, and everything works just fine.
I suggest you update your BM version.
If it still crashes after that, feel free to let us know here.

**Comment by digitalseraphim** [comment]
Using BloodMagic{1.9.4-2.0.2-48}, and evilcraft{0.10.2} I am getting this error. Looks like the SoulNetwork class was moved from "WayofTime.bloodmagic.api.network.SoulNetwork" to "WayofTime.bloodmagic.api.saving.SoulNetwork", which is why the code in the evilcraft 0.10.2 jar doesn't work, while compiling even the same code that was used to build 0.10.2 against the latest BM works, and the 0.10.2 jar that exists does not work. You don't actually import the SoulNetwork class directly, as you never save an instance of it, but you use it indirectly, as the return value of "getSoulNetwork" so the jar file that is uploaded to curse includes the old package name.

**Comment by rubensworks** [comment]
@digitalseraphim Ah, it seems you're right. I didn't notice the existence of da5ee2ac7a4faa50b55e44be62892798743dfba5 yet, which is why it worked for me.
This means that release 0.10.3 will be compatible with BM newest versions.
