### ISSUE TITLE
Crash when entering Nether Minecraft 1.11.2

### ISSUE THREAD

**Issue by Pynter** [rubensworks/EvilCraft#510]
Forge log link: http://pastebin.com/ny3W3nQY

Problem: Crash when entering Nether

Expected behaviour: Not Crashing when entering Nether

Steps to reproduce the problem: Have this mod installed and entering the Nether, it might be only on my hardware but I installed this mod with only Cyclops Core and Forge 13.20.0.2213, made sure I had the latest drivers on everything but it still crashed.
-
-

**Comment by kreezxil** [comment]
Happens when entering the nether.

in version 1.11.2-0.10.17

server crash log: https://gist.github.com/ProsperCraft/8fad1b93b2f900ed45b37bd1a44dd377

I see you say the bug is closed but the last time mod was updated on CurseForge was January 4, it is now January 19, almost a full 2 weeks later. 

Cheers!

**Comment by rubensworks** [comment]
@kreezxil That's correct, the fix was only implemented three days ago.

**Comment by ProsperCraft** [comment]
I think what he is trying to say is we need a 1.11.2 version, there appears to be a 1.10.2 bit. It 1.11.2 updated version.

Thank you as this will help us to not have the server crashing when people go there.
