### ISSUE TITLE
World is crashing while pregenerating.

### ISSUE THREAD

**Issue by Divineaspect** [rubensworks/EvilCraft#517]
Forge log link:
https://gist.github.com/Divineaspect/ccd158924da45d50ecf55e4ac322f820

Crashreport: https://gist.github.com/Divineaspect/19df56860c148f26d50d0d5e3025d767

Problem: World is crashing while pregenerating.

Expected behaviour: Not Crashing

Steps to reproduce the problem: Generating the world and it gets to evilcraft content.
using the latest test version of the Wanderlust Renewed pack, can share with you on atl if that'd help.

**Comment by rubensworks** [comment]
It's crashing on loot chest generation, so it's possible that another mod is causing this, but I'll look into it.

**Comment by Divineaspect** [comment]
I appreciate your attention to this issue.

**Comment by rubensworks** [comment]
@Divineaspect It looks like a mod you are using is causing a loot table entry with a `null` Item, which causes this crash.
This is not an EvilCraft issue, since this crash would also occur with regular vanilla loot chests.
I suggest that you try removing mods to see which one causes the issue. I know, these problems are hard to debug...

**Comment by Divineaspect** [comment]
Thank you for the time put into this.
