### ISSUE TITLE
Obscured Glass is not transparent.

### ISSUE THREAD

**Issue by thaumictom** [rubensworks/EvilCraft#611]
#### Issue type: :bug:
____
#### Short description:
Obscured Glass is not transparent.

#### Expected behaviour:
It's excepted that obscured glass is transparent, as it is transparent in inventory, but not when placed.

#### Actual behaviour:
It is not transparent.

#### Steps to reproduce the problem:
Place Obscured Glass.

#### Screenshot:
[https://imgur.com/BKOj4ko](url)
____
#### Versions:
- This mod: 0.10.38
- CyclopsCore: 0.10.22
- Minecraft: 1.12.2
- Forge: 14.23.0.2538

#### Log file:
None.

**Comment by rubensworks** [comment]
Are you using any mods that may be tweaking rendering-related things, such as optifine?

If so, please try reproducing this in a clean environment with such EC (and its requirements) installed.

**Comment by thaumictom** [comment]
I used FTB Horizons III with OptiFine, and I think it's because of Optifine. I searched through the options, and found nothing until now. Here is a picture of a clean enviroment: http://prntscr.com/hacrzi

Can you fix this mod so, that it works with OptiFine fine?

**Comment by josephcsible** [comment]
OptiFine is notoriously bad at mod compatibility, since it changes so much of vanilla's rendering in incompatible ways (it's a highly-invasive coremod), you can't see exactly what it's changing to work around it (since its source isn't public; a violation of Forge's coremod guidelines by the way), and it's exceptionally difficult for mod authors to test their mods against (since it doesn't have a development/deobfuscated build).

**Comment by rubensworks** [comment]
@ThaumicTom Sorry, but no. If you want to see this fixed, report it to the authors of Optifine.
