### ISSUE TITLE
Water is invisible through "auras" in this mod

### ISSUE THREAD

**Issue by josephcsible** [rubensworks/EvilCraft#631]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:

Water behind an environmental accumulator's beam, or a vengeance spirit, is invisible.

![2017-12-10_14 17 24](https://user-images.githubusercontent.com/16061266/33808464-dd75c8f4-ddb4-11e7-8c25-810500eb5302.png)

____
#### Versions:

Development version 61ae531, with all of its Gradle dependencies

#### Log file:

Nothing relevant

**Comment by rubensworks** [comment]
This has been like this since the beginning, simply because vanilla also rendered the beacon beam like that. But I just had a look, and it looks like vanilla fixed the issue, so we can reuse that fix.

**Comment by rubensworks** [comment]
Last commit fixes the EA beam.

As far as I can see, a similar fix for Vengeance Spirits is not possible (without some serious hacking).
This is because the beam is now rendered through the BufferBuilder with a custom alpha value, which takes into account all proper layers (such as water). The spirit renderer simply delegates this to the Entity renderer, which doesn't allow us to change the alpha value in the BufferBuilder.

Perhaps vanilla or Forge will change these things in the future. Until then, I'll close this issue. (I don't consider this important enough to spend too much time on it)
