### ISSUE TITLE
Humanoid flesh removed 2 hearts

### ISSUE THREAD

**Issue by jbossjaslow** [rubensworks/EvilCraft#643]
#### Issue type:

- :question: Question

After I had just started my world and had built a dark room for mobs to spawn, and Enderman appeared. I died a few times trying to kill it, and I wound up with some humanoid flesh as a result. I decided to eat it out of curiosity, and it permanently removed two hearts, leaving me with 8. I've tried killing myself, using instant health and regeneration potions, and looking in the config files, but I've found no answers. I also can't find much information about evilcraft online, and there is no wiki. How can I regain my two lost hearts?

**Comment by rubensworks** [comment]
Some other modmust be causing that. As you can see [here in the code](https://github.com/CyclopsMC/EvilCraft/blob/master-1.12/src/main/java/org/cyclops/evilcraft/item/WerewolfFlesh.java#L122-L125), the only thing that happens when you eat your own flesh, is that you will get the wither and blindness potion effects.

**Comment by jbossjaslow** [comment]
Thank you, I'll try to figure out what made it happen.
