### ISSUE TITLE
Vengeance focus compatibility issue with Thaumcraft BETA16

### ISSUE THREAD

**Issue by princessbinas** [rubensworks/EvilCraft#701]
#### Issue type:

- :bug: Bug

____

#### Short description:

NOTE: There is no crashing involved.

Upon installing BETA16 of Thaumcraft, EvilCraft's Vengeance Focus, an item that pushes defeated mobs' ghosts in to a Box of Eternal Closure stops working. The version of EvilCraft is not the problem as I have had it prior to installing Thaumcraft and it worked as intended. With Thaumcraft installed, the Vengeance Focus loses all functionality and is rendered useless.

#### Steps to reproduce the problem:

1. Install Thaumcraft, Thaumcraft JEI, Thaumcraft Periphery, and Thaumcraft Inventory Scanning with EvilCraft.
2. Obtain a Vengeance Focus and a Box of Eternal Closure.
3. Kill a mob and try to push it into the box with the Vengeance Focus.
5. See that the Vengeance Focus does absolutely nothing, not even emit a beam upon right click.

#### Expected behaviour:

I am supposed to be able to seal away the mob in the box and carry it back to a Spirit Furnace or store away the box for later use.

____

#### Versions:

- This mod: 0.10.58
- Minecraft: 1.12.2
- Forge: 14.23.4.2702

**Comment by rubensworks** [comment]
The Vengeance Focus has no TC interaction, so this does not look like an EC issue. Could you report it to the TC issue tracker as well?

**Comment by princessbinas** [comment]
I have and there was no reply on their end. It makes no sense as everything else after it in terms of posting date has been answered.
https://github.com/Azanor/thaumcraft-beta/issues/1009

**Comment by rubensworks** [comment]
I'll try debugging it when I find some time.

**Comment by princessbinas** [comment]
Okay. Thank you.

**Comment by princessbinas** [comment]
I have been told by Anazor that Thaumic Inventory Scanning could be causing the issue, which I do have in tandium with Thaumcraft, Thaumic JEI, and Thaumic Periphery. I was assuming they were not the root cause, but I will indeed reference both this thread, and the one I linked here to there and give the link to the new issue opened for Thaumic Inventory Scanning.

**Comment by rubensworks** [comment]
You could try removing the TC addons one-by-one to see which one effectively breaks it, and then you're certain which one causes the problem.

**Comment by princessbinas** [comment]
I will try that. Until I find the culprit on my end, I have this issue posted:
blay09/TCInventoryScanning#20

**Comment by princessbinas** [comment]
Sorry for the double post, but I can confirm now it is Thaumic Inventory Scanning is causing the issue. It was the first one I removed during my testing and the Vengeance Focus worked again.

**Comment by BlayTheNinth** [comment]
This issue is not happening to me in singleplayer using

- Minecraft Forge 14.23.4.2708
- Cyclops Core 0.11.6
- EvilCraft 0.10.58
- Thaumcraft 6.1.BETA16
- Thaumic Inventory Scanning 2.0.10

However, it is happening when playing on a server, and even when Thaumic Inventory Scanning is not loaded, so it's most likely an issue on EvilCraft's side after all. 

I assume the error occured in multiplayer, but you tested without Inventory Scanning in singleplayer, making it look as if the issue was solved by removing the mod.

**Comment by princessbinas** [comment]
I have tested with and without Inventory Scanning. I have used EvilCraft before with tons of other mods (the Dark MagicTech modpack to be exact) with NO ISSUES. Only when I removed Thaumic Inventory Scanning did Vengeance Focus work again. 

I have the following:
Forge 12.23.4.2705
Cyclops Core 0.11.6
EvilCraft 10.58
Thaumcraft 6.1.BETA16
Thaumic Inventory Scanning 2.0.10
Thaumic JEI 1.4.0-14

I thought I had Thaumic Periphery in the modpack, but it turns out I do not. I was must definitely in Single Player. I am not on a multiplayer server at this time nor was I when the glitch happened. Please note that I would have specified multiplayer if it were the case.

And as ruben said, EvilCraft DOES NOT interact with Thaumcraft in that way. It only provides extra essentia sources like condensed blood having essentia. Even Anazor confirmed this. It's your mod causing this issue, Blay09.

**Comment by BlayTheNinth** [comment]
I don't understand why you're choosing such a hostile tone, I'm just trying to help debug the issue you're having. Maybe my post was misunderstood. I was suggesting a possible reason as to what could have made you think my mod was the cause - it wouldn't have been the first time someone falsely believed one of my mods is causing a problem when really they were just coincidentally no longer experiencing the issue after removal.

I've realized my error during my multiplayer test (I was using a swarm instead of a dead mob, which can not be captured). However, that just means I'm not experiencing this issue at all, both singleplayer and multiplayer, with or without Thaumic Inventory Scanning. 

Did you try this on an instance with *only* those mods, or do you have other (non-Thaumcraft related) mods installed? Even if there's no crash, a log snippet of when the item is being used might help; there are cases where exceptions do not cause a crash, but still end up being logged.

Fact is, Inventory Scanning is a tiny mod that does nothing that should compromise the functionality of EvilCraft. Whether EvilCraft interacts with Thaumcraft does not make any difference, similarly you could say Inventory Scanning does not interact with EvilCraft.

**Comment by princessbinas** [comment]
I was not trying to be hostile. Sorry if I came across that way. I was trying to be as to the point as possible as you are sounding like you do not understand me at all and it is not the first time no one has understood a word I have said. I swear I speak Engrish rather than English some times. Small tangent.

I use the Dark MagicTech Modpack by the way. And I actually got a theory now. I just put it back in after riggerous testing the first time I had it in, removal, and after. Here's what I figured out. It occurs on a brand new world, which is what I had upon using your mod. After removal and reinsertion, it does work, but I think it is a sporadic bug that comes and goes. I have used Thaumcraft and EvilCraft together before, and this bug has never occurred when those two were together. I suspect this maybe a rare bug that needs to be looked into.

**Comment by rubensworks** [comment]
I should have some time later today to finally start debugging this, so that we can put this issue to rest :-) I guess it'll be something small.

**Comment by rubensworks** [comment]
So, I did some testing, and I wasn't able to reproduce this problem myself with EC, TC and IC installed.

@princessbinas You mentioned that you think that this is a "sporadic bug that comes and goes". Do you know in which situations you encountered the problem? If not, please let me know if you would come across it again in the future.
Also, when the focus is _broken_, what happens exactly? When you use it, does its icon still change and move in front of the player, or are you even not able to start using the item?
