### ISSUE TITLE
Looks like veined scribing tools are broken in compat

### ISSUE THREAD

**Issue by vdrake77** [rubensworks/EvilCraft#712]
#### Issue type:

- :bug: Bug

____

#### Short description:

Can't start minecraft, crashes on loading evilcraft-compat

#### Steps to reproduce the problem:

1. Start minecraft

#### Expected behaviour:

____

#### Versions:

- This mod: 10.61
- Minecraft: 1.12.2
- Forge: 2738

#### Log file:

https://pastebin.com/5dYVKy4a

**Comment by MentalMouse** [comment]
"Infused scribing tools"?  What mod would that be from?  I don't see any "Evilcraft-compat" mod on Curseforge.

**Comment by vdrake77** [comment]
Evilcraft compat is built in to evilcraft, to my understanding.  Also, my bad, I meant 'veined scribing tools', it's part of the thaumcraft compat.

**Comment by vdrake77** [comment]
https://pastebin.com/FHcpeVeP  Is a full crashlog.

It's something with Astral Sorcery and Evilcraft not playing well together, if I drop down to Astral 1.9.3 it's fine.

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/FHcpeVeP">---- Minecraft Crash Report ----    WARNING: coremods are present:    BCModPlugi - Pastebin.com</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
An infinite loop... It looks like AS is doing some kind of iteration over all items, which doesn't seem to work well with capabilities.

**Comment by esotericist** [comment]
I've also experienced this problem with [Food Funk](https://minecraft.curseforge.com/projects/food-funk).

The simple, easy solution would have been to disable the offending item, but there doesn't seem to be a way to disable the veined scribing tools without also disabling the rest of the thaumcraft compatibility. Is there any chance that could get broken out a little bit further?

Edit: To be clear, the problem definitely goes away when the Thaumcraft compatibility in evilcraft is disabled. So the problem seems to be specifically in the veined scribing tools.

**Comment by rubensworks** [comment]
@esotericist Could you share your crashlog?

The item should be disableable in the evilcraftcompat config file though, under the items section. Please report it in a separate issue if this isn't the case.

**Comment by esotericist** [comment]
@rubensworks I don't have ready access to the crash log right now, I'm afraid (and I removed the mods in question to continue getting other work done). I can try to generate a fresh one tomorrow.

As for the config, I somehow repeatedly failed to see the separate item config due to the structure. I think my brain only looks for sub-options after the master option, rather than above?

edit: Either way, tomorrow I'll both get you that log, and test if JUST disabling the item will do the job (I suspect it will)

**Comment by flamechair** [comment]
Also experiencing this: https://gist.github.com/iamtpage/9447c149abdf370bc75e069b80cfd56a

<blockquote><img src="https://avatars3.githubusercontent.com/u/8901422?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/iamtpage/9447c149abdf370bc75e069b80cfd56a">gist:9447c149abdf370bc75e069b80cfd56a</a></strong></div><div>GitHub is where people build software. More than 28 million people use GitHub to discover, fork, and contribute to over 85 million projects.</div></blockquote>

**Comment by Sunconure11** [comment]
I think the culprit could be astral sorcery. @Hellfirepvp

https://pastebin.com/GWaQ2kKB

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/GWaQ2kKB">---- Minecraft Crash Report ----  // Don't be sad, have a hug! <3    Time: 2018- - Pastebin.com</a></strong></div></blockquote>

**Comment by esotericist** [comment]
@rubensworks Here's the [crashlog you requested](https://gist.github.com/esotericist/a60c3d9007c0fef9cbf6d303d8195218). Food funk does an 'iterate over all the things ever' step similar to astral sorcery, and ends up in a tragically similar place. 

I'm on an older version of Astral Sorcery, so it isn't having this problem right now (although I plan to get the current version now that I know I can turn off the veined scribing tool).
