### ISSUE TITLE
Rejuvenated Flesh does not work with the Dark Utilities' Gluttony Charm

### ISSUE THREAD

**Issue by Jkosio23** [rubensworks/EvilCraft#727]
#### Issue type:

- :bug: Bug

____

#### Short description:

The Rejuvenated Flesh does not get eaten instantly as is intended by the charm. 

#### Steps to reproduce the problem:

1. Obtain both Rejuvenated Flesh and Gluttony Charm
2. Attempt to eat Rejuvenated Flesh

#### Expected behaviour:

The Rejuvenated flesh should instantly be eaten as per normal food when wearing the charm.

____

#### Versions:

- This mod: 1.12.2-0.10.62
- Minecraft: 1.12.2
- Forge: 14.23.4.2707
- Dark Utilities: 1.12.2-1.8.211

#### Log file:

Will post if asked for.

**Comment by Jkosio23** [comment]
I'm pretty sure this is because Rejuvenated Flesh doesn't actually register as a food? Seeing as it doesn't show any hunger restoration on its tooltip.

**Comment by rubensworks** [comment]
This item is indeed a special type of food, since it's not actually being fully consumed (item disappears) when eaten. That may be the reason why it's not fully compatible with food-handling mods.

I can have a look to see if this can be resolved easily.

**Comment by rubensworks** [comment]
So it looks like the Gluttony Charm checks if an item is instance of `ItemFood`, which makes sense.

However, Rejuvenated Flesh is not an instance of `ItemFood`. Mainly because it is not fully compatible with its interface. It may be possible to make it compatible, but this would break/reduce some existing functionality of the Flesh, which I don't want.

So I won't be fixing this, perhaps I might change my mind in a future major MC update (like 1.13).
