### ISSUE TITLE
Display Stand -- piping items and fluids in/out

### ISSUE THREAD

**Issue by belathus** [rubensworks/EvilCraft#778]
#### Issue type:

- :bug: Bug

____

#### Short description:

I am trying to automate the movement of items in and out of a portable inventory through a display stand. I've had very little success.

#### Steps to reproduce the problem:

1. **Success:** I tried a vanilla hopper. This was the one scenario I had success. A hopper was able to move items both into and out of a wooden exalted crafter
1. **Failure:** However, I was not able to move items in/out of a normal exalted crafter, Forestry backpacks, or Immersive Engineering crates with a hopper.
1. **Failure:** Tried moving items in/out of the display stand through EnderIO's item conduits with no success. The conduit connects to the top and bottom, but no items move. The conduit doesn't even connect to the side of the display stand.
1. **Failure:** I tried a wooden hopper (Tinker's Construct) with similar results -- no items move.
1. **Failure:** I then tried moving fluids out of a blood extractor, but the EIO fluid conduit wouldn't connect to the display stand.
1. **Failure:** Using Immersive Engineering's pump also did not work for moving fluids, no matter how I oriented the display stand.
1. I did not try transferring energy.

#### Expected behaviour:

I understand that the display stand is supposed to be able to allow you to move items, fluid, and energy into/out of storage items, but it seems to rarely work.

____

#### Versions:

- This mod: 0.10.75
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

#### Log file:

No crashes, though if you want to see a log, I'm sure I can grab one.

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by rubensworks** [comment]
So I did some testing, and there _does_ seem to be an issue with fluids, which I will fix shortly.

However, all other things seem to work fine for me.
As mentioned in the book, items can be piped in/out from the top and bottom side.
If you want to access the capabilities (item, fluid, energy, ...) of the item itself, you need to access any of the other sides. (Note that you can rotate display stands)

For example, this setup allows items to be moved through an exalted crafter:

![2019-06-24_17 53 32](https://user-images.githubusercontent.com/440384/60033538-a9d8c400-96a0-11e9-82b9-36818e000a4b.png)

I assume you tried connecting EnderIO's item conduits before there was a valid item available in the display stand, in which case it is normal that the conduits don't connect, since the conduits do not detect any valid item handler. Once you insert a valid item, the conduits should connect.

FYI, it is possible (untested) that Forestry backpacks and Immersive Engineering crates do not expose item handler capabilities on the items, in which case this setup will not work.
