### ISSUE TITLE
Crash with IC2 Classic

### ISSUE THREAD

**Issue by Prunoideae** [rubensworks/EvilCraft#785]
#### Issue type:

- :bug: Bug

____

#### Short description:
EvilCraft crashed when trying to load compact recipe for ICEXP, but there's only IC2 Classic installed.

#### Steps to reproduce the problem:

1. Install ONLY IC2 Classic, and EvilCraft and Cyclops Core.
2. Launch and wait for the crash
3. If only either EvilCraft or IC2 Classic is present, the crash will not happen.
#### Expected behaviour:
The recipes should not be loaded.

____

#### Versions:

- This mod: 1.12.2-0.10.77
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- IC2 Classic: 1.12-1.5.4.4

#### Log file:
https://pastebin.com/Kg0AHS7m

**Comment by rubensworks** [comment]
So the problem is that IC2 classic uses the same mod id as IC2 exp, which makes it impossible for me to distinguish between the two. Ideally, IC2 classic should use a different mod id, but last time I checked, the mod author of the fork was not willing to do this. So there is not much I can do about this on my end unfortunately.

You can however just disable the IC2 compat of EvilCraft (see config file). This will avoid loading the compat code, and will therefore not crash.
