### ISSUE TITLE
is a bood extractor in autosupply mode supposed to be able to fill any of the baubles?

### ISSUE THREAD

**Issue by DoomSquirter** [rubensworks/EvilCraft#805]
#### Issue type:

- :question: Question

____

#### Question:

is a bood extractor in autosupply mode supposed to be able to fill any of the baubles?

It does not do so in EvilCraft-1.12.2-0.10.78.  just verifying if this is something it's supposed to do and isn't working right or if it's not supposed to work in the first place.

using a invigorating pendant right now as an example.

**Comment by rubensworks** [comment]
It should fill baubles as well. If not, then this is probably a bug.
Could you try reproducing without any other mods installed?

**Comment by DoomSquirter** [comment]
used
Baubles-1.12-1.5.2
BloodMagic-1.12.2-2.4.3-105
CyclopsCore-1.12.2-1.6.3
EvilCraft-1.12.2-0.10.78
Guide-API-1.12-2.1.8-63
Guidebook-1.12.2-2.9.4
jei_1.12.2-4.15.0.293

does not fill bauble while it is in bauble slot.
I put pendant on, set extractor to auto supply mode
pendant had 5000 mb in it
set myself on fire
it removed the fire and had 2-3k left but never refilled
put bauble in hotbar and you hear bucket sounds and it fills the pendant

**Comment by rubensworks** [comment]
So I forgot about how this mod works (it has been years since I wrote it...).

The blood extractor will _only_ fill items that are active in your hotbar when in auto-supply mode. It will therefore not fill your baubles.

There is however the entangled chalice that has an _omni supply_ mode that will fill items in _all_ slots, including baubles slots.
