### ISSUE TITLE
Crash with EnderIO Intergration in 1.12

### ISSUE THREAD

**Issue by LocalBoomer** [rubensworks/EvilCraft#807]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Crash at startup with latest enderIO release. Seems to be some recipe manager issue with the compatibility module?

#### Steps to reproduce the problem:

1. Install evilcraft and enderIO 
2. launch
3. profit?

#### Expected behaviour:

It not to do this

#### Versions:

- This mod: EvilCraft-1.12.2-0.10.78
- Minecraft: 1.12.2
- Forge: 14.23.5.2854 

Extra Info
- EnderIO: 5.2.63
- CyclopsCore: 1.6.6
#### Log file:
[Crash Report](https://pastebin.com/DXeX4i95)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm having lots of issues getting this mod to build again, since many of the maven repos I depend on for retrieving mods seem to be dead.
I won't invest any more time in this, since 1.12 is EOL anyways.
(If anyone else is up for this, feel free to submit a PR)

In any case, anyone experiencing this issue can simply disable EIO compact as follows:

**In `evilcraftcompat.cfg`, set the follow option to `false`**:
```
B:enderio=false
```
