### ISSUE TITLE
blood splash/blood particle accessing LegacyRandomSource from multiple threads crash

### ISSUE THREAD

**Issue by thlinter** [rubensworks/EvilCraft#954]
#### Issue type:

- :bug: Blood splash crash or blood particle

____

#### Short description:

blood particle or blood splash led to crash (Accessing LegacyRandomSource from multiple threads)

same issues as https://github.com/CyclopsMC/EvilCraft/issues/949
(on atm8)

#### Steps to reproduce the problem:

1. randomly appeared and constantly

#### Expected behaviour: mob farming with other machines then prob too much blood it crashed

____

#### Versions:

- This mod: [EvilCraft-1.19.2-1.2.10.jar]-
-  Minecraft: 1.19.2
- Forge: 43.1.55

**Comment by rubensworks** [comment]
Related to #949

**Comment by GetJaped** [comment]
Hello! Same issue here, though I've yet to set up a mob grinder. In fact, this frequently occurs as I'm just walking around the world. It happens more often in the End I've discovered, presumably because Enderman can teleport high up and then fall, causing a bloodstain which causes the particles which I assume causes the crash. Here's my log, if it helps: https://mclo.gs/KBNrCId

<blockquote><img src="img/favicon.ico" width="48" align="right"><div>mclo.gs</div><div><strong><a href="https://mclo.gs/KBNrCId">Forge 1.19.2 Crash Report [#KBNrCId]</a></strong></div><div>707 lines</div></blockquote>

**Comment by ayymoan** [comment]
https://mclo.gs/3e5nlFZ

<blockquote><img src="img/favicon.ico" width="48" align="right"><div>mclo.gs</div><div><strong><a href="https://mclo.gs/3e5nlFZ">Forge 1.19.2 Client Log [#3e5nlFZ]</a></strong></div><div>3281 lines | 23 errors</div></blockquote>

**Comment by SoulzBAen** [comment]
Been getting this issue consistently for the last three days. Making the pack(ATM 8) almost completely unplayable.

https://mclo.gs/vOYTBqr

**Comment by DerpyFrood0421** [comment]
Also seeing this crash in ATM8 (1.0.6b). Oddly I don't recall this being an issue in 1.0.5, which included the older version of EvilCraft - I'm going to try downgrading EvilCraft and see if it helps.

**Comment by Ninjawolf0007** [comment]
After updating the ATM8 modpack to version 1.0.7, where EvilCraft was updated to version 1.2.12, I've started to receive this crash again after a few hours of play.
[crash-2022-12-26_13.19.15-server.txt](https://github.com/CyclopsMC/EvilCraft/files/10304829/crash-2022-12-26_13.19.15-server.txt)
