### ISSUE TITLE
unusing enchantment probibits some pickaxes with infinite durability from working 

### ISSUE THREAD

**Issue by Matshgi** [rubensworks/EvilCraft#993]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When using the unusing enchantment on Pickaxes with Infinite Durability, for example the Awakened Supremium Pickaxe from the Mystical Agriculture Mod, the Pickaxe can't break the block because the block will keep reappearing.

#### Steps to reproduce the problem:

1. Enchant Awakened Supremium Pickaxe with unusing
2. Try to break a block

#### Expected behaviour:

The block should break.

____

#### Versions:

- This mod: 1.2.25
- Minecraft: 1.20.1
- Forge: 47.1.1

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
The unusing enchantment will check if the current durability is 5 or less from the max durability, it will block changes in the durability and avoid the block destroy action.
So if the pickaxe you're using has a max durability of 5 or less (and handles the infinite durability in some other manner), this behaviour definitely makes sense.

Since unusing+infinite durability don't really make sense, I would recommend just not using them together.
I could add some kind of blacklist mechanism to make these two things just not possible in the first place if you think that makes sense?
